### ISSUE TITLE
It seems incompatible for Python3

### ISSUE THREAD

**Issue by tangg555** [timvieira/arsenal#2]
qaq

**Comment by tangg555** [comment]
emmm... I downloaded your repository and installed that through "python setup.py install " as well. But when I ran your CRF code (which imports arsenal package) I found it throws errors showing the arsenal code is py2 style.

**Comment by timvieira** [comment]
First, which CRF package?  I have two:
1. [crf](https://github.com/timvieira/crf)) - very simple implementation meant for teaching CRFs
2. [vocrf](https://github.com/timvieira/vocrf) - fast (cython) and includes structure learning

I'm guessing that you are talking about implementation 1.  I have pushed some changes to this repo which should now support Python 3. 

Try pulling the latest versions of `arsenal` and `crf` and let me know if it all works!

**Comment by tangg555** [comment]
Oh, thank you very much ;P. Yes it's about implemention 1. I've just tried that after downloading these repositories again and now the py2 error seems gone but it throwes another error as follows:
Traceback (most recent call last):
  File "C:/Users/46312/Desktop/python-practice/NLP/pythonNLP/StatisticalLanguageModeling(SLM)/11.CRF/crf-master/crf/example.py", line 29, in <module>
    from crf.stringcrf import Instance, Token, StringCRF, build_domain
  File "E:\extrasoftware\Python\Python3.6\lib\site-packages\crf-1.0-py3.6.egg\crf\stringcrf.py", line 4, in <module>
    from crf.basecrf import CRF
  File "E:\extrasoftware\Python\Python3.6\lib\site-packages\crf-1.0-py3.6.egg\crf\crf.py", line 13, in <module>
ModuleNotFoundError: No module named 'arsenal.math'

**Comment by timvieira** [comment]
That is not the latest version of the `crf` package.  In the latest version, there is no file called `crf.py`.

**Comment by tangg555** [comment]
Oh, I guess I get to find what's going wrong. I installed arsenal package and ran the example.py in 'crf ' dir without installing it. Therefore after removing the prefix 'crf .' it runs now. Thank you for your hard work, Tim. :-)
